name: ScoreboardFrame
main: kpqi.sf.MainSF
version: 1.4
author: Kpqi5858
description: Awesome Scoreboard plugin with PlaceHolderAPI. Made by 0verFlow(Kpqi5858)
softdepend: [PlaceholderAPI, VariableTriggers]
commands:
  runsf:
    description: Run scoreboard.
  clearsf:
    description: Clear scoreboard.
  scoreboardframe:
    description: About this plugin
  reloadsf:
    description: Reload scoreboard files.
  placeholdersf:
    description: Sets command placeholder.